publishDir = "public"
# baseURL = "https://www.timbaolan.com/"
languageCode = "en-us"
title = "motion / graphic / web design, web dev"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-43728553-1"
pluralizelisttitles = false

[params]
    author = "Bao-Lan Nguyen-Phuoc"
    description = "\n- After Effects, Premiere Pro, Hype, Google Web Designer \n- Photoshop, Illustrator, InDesign, Dimension, XD, Figma \n- Basics in Audition, C4D, Blender, 3DsMax \n- HTML, CSS (+ Foundation, Bootstrap, TailwindCSS), JavaScript (+ GSAP, React), PHP, MySQL, Hugo, Netlify, Wordpress, Webflow"
    githubUsername = "timbaolan"
    accent = "#0ae"
    showBorder = true
    backgroundColor = "#101215"
    font = "Open Sans" # should match the name on Google Fonts!
    google_fonts = [
        ["Gruppo"],
        ["Open Sans"]
    ]
    heading_font = "Gruppo"
    body_font = "Open Sans"
    highlight = true
    highlightStyle = "solarized-dark"
    # highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]


# [[menu.main]]
#     url = "/"
#     name = "Home"
#     weight = 1

[[menu.main]]
    url = "/motion_design/"
    name = "Motion Design"
    weight = 2

[[menu.main]]
    url = "/graphic_design/"
    name = "Graphic Design"
    weight = 3

[[menu.main]]
    url = "/web_design_and_dev/"
    name = "Web Design & Dev"
    weight = 4

[[menu.main]]
    url = "/digital_art/"
    name = "Digital Art"
    weight = 5





# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:baolan.np@gmail.com"
#     name = "envelope-o"
#     weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/baolan/"
    name = "linkedin"
    weight = 2

[[menu.icon]]
    url = "https://artstation.com/artist/timbaolan/"
    name = "artstation"
    weight = 3

[[menu.icon]]
    url = "https://github.com/timbaolan/"
    name = "github"
    weight = 4
